# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Core'
pod 'Firebase/Auth'

target 'footsy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for footsy

  target 'footsy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end